#!/usr/bin/env python3
"""
Rebrand tool: Praxis -> Colber

Bulk substitution across the working tree, with explicit exclusions for
files that must keep their original "Praxis" / "AgentStack" content for
historical reasons (NOTICE, CDC docx, etc.).

This is a one-shot tool, run once on 2026-05-01. Safe to keep in `.tools/`
for posterity. Idempotent — running it twice is a no-op.

Patterns substituted, in order (cases preserved):
  1. PRAXIS  -> COLBER   (env vars: PRAXIS_VM, PRAXIS_LIVE_TESTS, ...)
  2. Praxis  -> Colber   (docs, headings, brand mentions)
  3. praxis  -> colber   (catch-all: package names, db names, container
                          names, image names, gRPC namespaces, paths)

Files traversed: text-like extensions only (see ALLOWED_EXTS) and a few
specific filenames (Dockerfile, .env*, etc).

Files explicitly skipped (keep their Praxis/AgentStack content):
  - LICENSE, NOTICE                      (governance files just authored)
  - .tools/_rebrand.py                   (this file itself; references are
                                          allowed in identifiers)
  - docs/AgentStack_Cahier_des_charges.docx  (binary, frozen v1.0)
  - pnpm-lock.yaml                       (regenerated by pnpm install)
  - any path under .git/ or node_modules/
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ALLOWED_EXTS = {
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".json", ".yml", ".yaml", ".toml",
    ".md", ".mdx", ".txt",
    ".py", ".sh", ".ps1",
    ".sql", ".proto",
    ".env", ".example",
    ".gitignore", ".dockerignore", ".prettierignore",
}

# Files matched by exact basename (no extension or unusual extension)
ALLOWED_BASENAMES = {
    "Dockerfile", ".env.example", ".env.template",
    ".prettierrc.json", ".eslintrc", "tsconfig.json",
    "turbo.json", "package.json", "pnpm-workspace.yaml",
    ".editorconfig", ".gitattributes", ".npmrc", ".nvmrc",
    "eslint.config.js", "drizzle.config.ts",
}

# Hard skip — these files keep their Praxis content intact
SKIP_RELATIVE = {
    "LICENSE",
    "NOTICE",
    "pnpm-lock.yaml",
    ".tools/_rebrand.py",
    "docs/AgentStack_Cahier_des_charges.docx",
}

# Skip any path containing these directory components
SKIP_DIR_COMPONENTS = {".git", "node_modules", ".next", "dist", "build", ".turbo"}

SUBSTITUTIONS = [
    ("PRAXIS", "COLBER"),
    ("Praxis", "Colber"),
    ("praxis", "colber"),
]


def is_eligible(path: Path) -> bool:
    rel = path.relative_to(ROOT).as_posix()
    if rel in SKIP_RELATIVE:
        return False
    parts = set(path.relative_to(ROOT).parts)
    if parts & SKIP_DIR_COMPONENTS:
        return False
    if path.name.startswith(".env"):
        return True
    if path.name in ALLOWED_BASENAMES:
        return True
    if path.name == "Dockerfile" or path.name.startswith("Dockerfile."):
        return True
    suffix = path.suffix.lower()
    if suffix in ALLOWED_EXTS:
        return True
    return False


def rewrite_file(path: Path) -> int:
    try:
        original = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return 0
    rewritten = original
    for old, new in SUBSTITUTIONS:
        rewritten = rewritten.replace(old, new)
    if rewritten == original:
        return 0
    path.write_text(rewritten, encoding="utf-8", newline="")
    # Count occurrences changed
    return sum(original.count(old) for old, _ in SUBSTITUTIONS)


def main() -> int:
    touched: list[tuple[str, int]] = []
    total = 0
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIR_COMPONENTS]
        for fname in filenames:
            path = Path(dirpath) / fname
            if not is_eligible(path):
                continue
            n = rewrite_file(path)
            if n:
                touched.append((path.relative_to(ROOT).as_posix(), n))
                total += n
    print(f"Rewrote {len(touched)} files, {total} substitutions total")
    for rel, n in sorted(touched):
        print(f"  {n:4d}  {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
